### ISSUE TITLE
Create a page with other resources and tips

### ISSUE THREAD

**Issue by gforsyth** [barbagroup/essential_skills_RRC#41]
There's always going to be a bunch of stuff we don't have time to cover, but we can provide a list of helpful services / links.

e.g.

- For publishing datasets publicly and getting an associated DOI, use Zenodo

what else?

**Comment by labarba** [comment]
* For publishing research software: submit to the [Journal of Open Source Software](http://joss.theoj.org)
* For replication studies: submit to [The ReScience Journal](http://rescience.github.io)
* Submit preprints! [arXiv](https://arxiv.org) for physics, computer science, mathematics, quantitative biology, quantitative finance, statistics; [bioRxiv](http://biorxiv.org) for all subject areas of biology; [socArXiv](https://socopen.org) for social sciences; [engrXiv](https://osf.io/preprints/engrxiv/) for engineering.
* For sharing figures, presentations, posters, short reports and more: [Figshare](https://figshare.com)

**Comment by ncclementi** [comment]
* For collaborative writing  [Authorea](https://www.authorea.com/)  and [ShareLaTeX](https://www.sharelatex.com/)
