### ISSUE TITLE
Change keyword arguments in python scientific stack

### ISSUE THREAD

**Issue by ncclementi** [barbagroup/essential_skills_RRC#46]
We should change the scientific stack notebooks to use the long form of the keyword arguments for educational purposes. e.g. `linestyle` instead of `ls`

Thanks @labarba for pointing this out

**Comment by ncclementi** [comment]
Solved! Push it directly to master because it was a minor change!
@gforsyth when you can, please generate the new `md` corresponding to the updated notebook and close the issue when it's done! Thanks!

**Comment by gforsyth** [comment]
Closed via 534878c
